version: '3.9'

services:
  postgres-users:
    image: postgres:latest
    container_name: cashback-postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=coolpassword
      - POSTGRES_DB=cashback
    ports:
      - "6432:5432"
    restart: unless-stopped